import { keys, events } from '../constants';

export const swiperConfig = {
    SLIDES_LOOP: true,
    SLIDES_PER_VIEW: 1,
    SLIDES_GAP: 20,
    SLIDES_TRANSITION_TIME: 750,
    SLIDES_AUTOPLAY_DELAY: 2000,
    SLIDES_AUTOPLAY_INTERACTION_DISABILITY: false,
    SLIDES_ACCESSIBILITY: true,
    SLIDES_PAGINATION_CLICKABILE: true,
    SLIDES_KEYBOARD_CONTROL: true,
    SLIDES_ONLY_IN_VIEWPORT: true,
    SLIDES_NEXT_NAVIGATION_ELEMENT: 'btn--next',
    SLIDES_PREVIOUS_NAVIGATION_ELEMENT: 'btn--prev',
    SLIDES_NAVIGATION_EVENT: events.KEYDOWN,
    SLIDES_NEXT_CONTROLLER: keys.ARROW_RIGHT,
    SLIDES_PREVIOUS_CONTROLLER: keys.ARROW_LEFT,
};
